# Generated by Django 3.0.6 on 2020-05-24 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='platNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Car'),
        ),
    ]
