# Generated by Django 3.0.6 on 2020-05-26 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200526_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Car'),
        ),
    ]
