# Generated by Django 3.0.6 on 2020-06-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200603_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.TimeField(default='01:00:00'),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Car'),
        ),
    ]
