# Generated by Django 3.0.6 on 2020-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200603_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='endlocation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startlocation',
            field=models.CharField(max_length=255),
        ),
    ]
