# Generated by Django 3.0.6 on 2020-06-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200603_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='active',
            new_name='status',
        ),
    ]
