# Generated by Django 3.0.6 on 2020-06-04 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200603_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Car'),
        ),
    ]
